aliyun:
  oss:
    #yourEndpoint填写Bucket所在地域对应的Endpoint，可在创建好的Bucket概况页查看。
    endpoint: oss-cn-beijing.aliyuncs.com
    # 以成都为例，Endpoint填写为https://oss-cn-chengdu.aliyuncs.com
    #阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户
    accessKeyId: LTAI5t5ZbD71qx5ENKSkFHjK
    # 阿里云账号AccessKey里所对应的AccessKey ID
    accessKeySecret: 1KyrA2bNbW0bhuCV0r7pBcy7r3iSP6
    # 阿里云账号AccessKey里所对应的AccessKey Secret
    bucketName: aliyunxiaowang       # OSS对象存储空间名

